services:
  db:
    image: postgres:latest
    container_name: tui-db
    restart: always
    env_file:
      - db/database.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: app
    container_name: tui-app
    depends_on:
      - db
    env_file:
      - db/database.env
    stdin_open: true
    tty: true
    entrypoint: ["/app/main"]

volumes:
  pgdata: