services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    env_file:
      - database.env

volumes:
  pgdata: